services:
  yolo-train:
    user: "${UID}:${GID}"
    build:
      context: ..            
      dockerfile: docker/Dockerfile
    
    container_name: yolo_trainer
    ipc: host
    working_dir: /usr/src
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - ../datasets:/usr/src/datasets  
      - ..:/usr/src
      - /tmp/.X11-unix:/tmp/.X11-unix 
    tty: true
    stdin_open: true
    command: tail -f /dev/null